local gui = Instance.new("ScreenGui")
gui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
local label = Instance.new("TextLabel")
label.Text = "Visit The Nerd Channel For The Last Update!"
label.Size = UDim2.new(1, 0, 1, 0) 
label.Position = UDim2.new(0, 0, 0, 0) 
label.TextColor3 = Color3.new(1, 1, 1) 
label.BackgroundTransparency = 1 
label.FontSize = Enum.FontSize.Size48
label.Parent = gui
